module dds {
    struct Message {
      string message;
    };
    #pragma keylist Message message

    struct MessageAlt {
      short user_id;
      string message;
    };
    #pragma keylist MessageAlt message
};
